using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace IAD.Shell
{
    partial class RoiManagerDialog
    {
        private IContainer components = null;
        private TableLayoutPanel rootLayout;
        private DataGridView dgvRois;
        private DataGridViewTextBoxColumn colName;
        private DataGridViewTextBoxColumn colType;
        private DataGridViewTextBoxColumn colX;
        private DataGridViewTextBoxColumn colY;
        private DataGridViewTextBoxColumn colW;
        private DataGridViewTextBoxColumn colH;
        private DataGridViewTextBoxColumn colAngle;
        private DataGridViewTextBoxColumn colState;
        private GroupBox grpEditor;
        private TableLayoutPanel editorLayout;
        private Label lblName;
        private Label lblType;
        private Label lblCenterX;
        private Label lblCenterY;
        private Label lblWidth;
        private Label lblHeight;
        private Label lblAngle;
        private Label lblSort;
        private TextBox txtName;
        private ComboBox cboType;
        private NumericUpDown numCenterX;
        private NumericUpDown numCenterY;
        private NumericUpDown numWidth;
        private NumericUpDown numHeight;
        private NumericUpDown numAngle;
        private NumericUpDown numSort;
        private CheckBox chkEnabled;
        private FlowLayoutPanel buttonPanel;
        private Button btnNew;
        private Button btnEdit;
        private Button btnSave;
        private Button btnDelete;
        private Button btnClose;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new Container();
            this.rootLayout = new TableLayoutPanel();
            this.dgvRois = new DataGridView();
            this.colName = new DataGridViewTextBoxColumn();
            this.colType = new DataGridViewTextBoxColumn();
            this.colX = new DataGridViewTextBoxColumn();
            this.colY = new DataGridViewTextBoxColumn();
            this.colW = new DataGridViewTextBoxColumn();
            this.colH = new DataGridViewTextBoxColumn();
            this.colAngle = new DataGridViewTextBoxColumn();
            this.colState = new DataGridViewTextBoxColumn();
            this.grpEditor = new GroupBox();
            this.editorLayout = new TableLayoutPanel();
            this.lblName = new Label();
            this.lblType = new Label();
            this.lblCenterX = new Label();
            this.lblCenterY = new Label();
            this.lblWidth = new Label();
            this.lblHeight = new Label();
            this.lblAngle = new Label();
            this.lblSort = new Label();
            this.txtName = new TextBox();
            this.cboType = new ComboBox();
            this.numCenterX = new NumericUpDown();
            this.numCenterY = new NumericUpDown();
            this.numWidth = new NumericUpDown();
            this.numHeight = new NumericUpDown();
            this.numAngle = new NumericUpDown();
            this.numSort = new NumericUpDown();
            this.chkEnabled = new CheckBox();
            this.buttonPanel = new FlowLayoutPanel();
            this.btnNew = new Button();
            this.btnEdit = new Button();
            this.btnSave = new Button();
            this.btnDelete = new Button();
            this.btnClose = new Button();
            this.rootLayout.SuspendLayout();
            ((ISupportInitialize)(this.dgvRois)).BeginInit();
            this.grpEditor.SuspendLayout();
            this.editorLayout.SuspendLayout();
            ((ISupportInitialize)(this.numCenterX)).BeginInit();
            ((ISupportInitialize)(this.numCenterY)).BeginInit();
            ((ISupportInitialize)(this.numWidth)).BeginInit();
            ((ISupportInitialize)(this.numHeight)).BeginInit();
            ((ISupportInitialize)(this.numAngle)).BeginInit();
            ((ISupportInitialize)(this.numSort)).BeginInit();
            this.buttonPanel.SuspendLayout();
            this.SuspendLayout();

            this.rootLayout.ColumnCount = 1;
            this.rootLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.rootLayout.Controls.Add(this.dgvRois, 0, 0);
            this.rootLayout.Controls.Add(this.grpEditor, 0, 1);
            this.rootLayout.Controls.Add(this.buttonPanel, 0, 2);
            this.rootLayout.Dock = DockStyle.Fill;
            this.rootLayout.Padding = new Padding(14);
            this.rootLayout.RowCount = 3;
            this.rootLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 58F));
            this.rootLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 42F));
            this.rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 58F));

            this.dgvRois.AllowUserToAddRows = false;
            this.dgvRois.AllowUserToDeleteRows = false;
            this.dgvRois.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvRois.BackgroundColor = Color.White;
            this.dgvRois.Columns.AddRange(new DataGridViewColumn[] { this.colName, this.colType, this.colX, this.colY, this.colW, this.colH, this.colAngle, this.colState });
            this.dgvRois.Dock = DockStyle.Fill;
            this.dgvRois.MultiSelect = false;
            this.dgvRois.ReadOnly = true;
            this.dgvRois.RowHeadersVisible = false;
            this.dgvRois.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            this.dgvRois.CellDoubleClick += new DataGridViewCellEventHandler(this.dgvRois_CellDoubleClick);

            this.colName.HeaderText = "ROI名称";
            this.colName.Name = "colName";
            this.colType.HeaderText = "类型";
            this.colType.Name = "colType";
            this.colX.HeaderText = "CenterX";
            this.colX.Name = "colX";
            this.colY.HeaderText = "CenterY";
            this.colY.Name = "colY";
            this.colW.HeaderText = "Width";
            this.colW.Name = "colW";
            this.colH.HeaderText = "Height";
            this.colH.Name = "colH";
            this.colAngle.HeaderText = "Angle";
            this.colAngle.Name = "colAngle";
            this.colState.HeaderText = "状态";
            this.colState.Name = "colState";

            this.grpEditor.Controls.Add(this.editorLayout);
            this.grpEditor.Dock = DockStyle.Fill;
            this.grpEditor.Text = "ROI 参数";

            this.editorLayout.ColumnCount = 6;
            this.editorLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 16.666F));
            this.editorLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 16.666F));
            this.editorLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 16.666F));
            this.editorLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 16.666F));
            this.editorLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 16.666F));
            this.editorLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 16.67F));
            this.editorLayout.Controls.Add(this.lblName, 0, 0);
            this.editorLayout.Controls.Add(this.lblType, 1, 0);
            this.editorLayout.Controls.Add(this.lblCenterX, 2, 0);
            this.editorLayout.Controls.Add(this.lblCenterY, 3, 0);
            this.editorLayout.Controls.Add(this.lblWidth, 4, 0);
            this.editorLayout.Controls.Add(this.lblHeight, 5, 0);
            this.editorLayout.Controls.Add(this.txtName, 0, 1);
            this.editorLayout.Controls.Add(this.cboType, 1, 1);
            this.editorLayout.Controls.Add(this.numCenterX, 2, 1);
            this.editorLayout.Controls.Add(this.numCenterY, 3, 1);
            this.editorLayout.Controls.Add(this.numWidth, 4, 1);
            this.editorLayout.Controls.Add(this.numHeight, 5, 1);
            this.editorLayout.Controls.Add(this.lblAngle, 0, 2);
            this.editorLayout.Controls.Add(this.lblSort, 1, 2);
            this.editorLayout.Controls.Add(this.numAngle, 0, 3);
            this.editorLayout.Controls.Add(this.numSort, 1, 3);
            this.editorLayout.Controls.Add(this.chkEnabled, 2, 3);
            this.editorLayout.Dock = DockStyle.Fill;
            this.editorLayout.Padding = new Padding(10, 8, 10, 8);
            this.editorLayout.RowCount = 4;
            this.editorLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
            this.editorLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 38F));
            this.editorLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 26F));
            this.editorLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 38F));

            this.lblName.Dock = DockStyle.Fill;
            this.lblName.Text = "ROI名称";
            this.lblName.TextAlign = ContentAlignment.BottomLeft;
            this.lblType.Dock = DockStyle.Fill;
            this.lblType.Text = "ROI类型";
            this.lblType.TextAlign = ContentAlignment.BottomLeft;
            this.lblCenterX.Dock = DockStyle.Fill;
            this.lblCenterX.Text = "CenterX";
            this.lblCenterX.TextAlign = ContentAlignment.BottomLeft;
            this.lblCenterY.Dock = DockStyle.Fill;
            this.lblCenterY.Text = "CenterY";
            this.lblCenterY.TextAlign = ContentAlignment.BottomLeft;
            this.lblWidth.Dock = DockStyle.Fill;
            this.lblWidth.Text = "Width";
            this.lblWidth.TextAlign = ContentAlignment.BottomLeft;
            this.lblHeight.Dock = DockStyle.Fill;
            this.lblHeight.Text = "Height";
            this.lblHeight.TextAlign = ContentAlignment.BottomLeft;
            this.lblAngle.Dock = DockStyle.Fill;
            this.lblAngle.Text = "Angle(deg)";
            this.lblAngle.TextAlign = ContentAlignment.BottomLeft;
            this.lblSort.Dock = DockStyle.Fill;
            this.lblSort.Text = "排序";
            this.lblSort.TextAlign = ContentAlignment.BottomLeft;

            this.txtName.Dock = DockStyle.Fill;
            this.cboType.Dock = DockStyle.Fill;
            this.cboType.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cboType.Items.AddRange(new object[] { "Rectangle", "Circle", "Polygon" });

            this.numCenterX.DecimalPlaces = 3;
            this.numCenterX.Dock = DockStyle.Fill;
            this.numCenterX.Maximum = 100000;
            this.numCenterX.Minimum = -100000;
            this.numCenterY.DecimalPlaces = 3;
            this.numCenterY.Dock = DockStyle.Fill;
            this.numCenterY.Maximum = 100000;
            this.numCenterY.Minimum = -100000;
            this.numWidth.DecimalPlaces = 3;
            this.numWidth.Dock = DockStyle.Fill;
            this.numWidth.Maximum = 100000;
            this.numHeight.DecimalPlaces = 3;
            this.numHeight.Dock = DockStyle.Fill;
            this.numHeight.Maximum = 100000;
            this.numAngle.DecimalPlaces = 3;
            this.numAngle.Dock = DockStyle.Fill;
            this.numAngle.Maximum = 360;
            this.numAngle.Minimum = -360;
            this.numSort.Dock = DockStyle.Fill;
            this.numSort.Maximum = 10000;
            this.chkEnabled.Dock = DockStyle.Fill;
            this.chkEnabled.Text = "启用";
            this.chkEnabled.TextAlign = ContentAlignment.MiddleLeft;

            this.buttonPanel.Controls.Add(this.btnClose);
            this.buttonPanel.Controls.Add(this.btnDelete);
            this.buttonPanel.Controls.Add(this.btnSave);
            this.buttonPanel.Controls.Add(this.btnEdit);
            this.buttonPanel.Controls.Add(this.btnNew);
            this.buttonPanel.Dock = DockStyle.Fill;
            this.buttonPanel.FlowDirection = FlowDirection.RightToLeft;
            this.buttonPanel.Padding = new Padding(0, 10, 0, 0);
            this.buttonPanel.WrapContents = false;

            this.btnClose.DialogResult = DialogResult.OK;
            this.btnClose.Margin = new Padding(8, 0, 0, 0);
            this.btnClose.Size = new Size(88, 34);
            this.btnClose.Text = "关闭";
            this.btnDelete.Margin = new Padding(8, 0, 0, 0);
            this.btnDelete.Size = new Size(88, 34);
            this.btnDelete.Text = "删除";
            this.btnDelete.Click += new System.EventHandler(this.btnDelete_Click);
            this.btnSave.Margin = new Padding(8, 0, 0, 0);
            this.btnSave.Size = new Size(100, 34);
            this.btnSave.Text = "新增 ROI";
            this.btnSave.Click += new System.EventHandler(this.btnSave_Click);
            this.btnEdit.Margin = new Padding(8, 0, 0, 0);
            this.btnEdit.Size = new Size(88, 34);
            this.btnEdit.Text = "编辑";
            this.btnEdit.Click += new System.EventHandler(this.btnEdit_Click);
            this.btnNew.Margin = new Padding(8, 0, 0, 0);
            this.btnNew.Size = new Size(88, 34);
            this.btnNew.Text = "新建";
            this.btnNew.Click += new System.EventHandler(this.btnNew_Click);

            this.AutoScaleDimensions = new SizeF(96F, 96F);
            this.AutoScaleMode = AutoScaleMode.Dpi;
            this.ClientSize = new Size(900, 580);
            this.Controls.Add(this.rootLayout);
            this.FormBorderStyle = FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "RoiManagerDialog";
            this.StartPosition = FormStartPosition.CenterParent;
            this.Text = "ROI 管理";

            this.rootLayout.ResumeLayout(false);
            ((ISupportInitialize)(this.dgvRois)).EndInit();
            this.grpEditor.ResumeLayout(false);
            this.editorLayout.ResumeLayout(false);
            this.editorLayout.PerformLayout();
            ((ISupportInitialize)(this.numCenterX)).EndInit();
            ((ISupportInitialize)(this.numCenterY)).EndInit();
            ((ISupportInitialize)(this.numWidth)).EndInit();
            ((ISupportInitialize)(this.numHeight)).EndInit();
            ((ISupportInitialize)(this.numAngle)).EndInit();
            ((ISupportInitialize)(this.numSort)).EndInit();
            this.buttonPanel.ResumeLayout(false);
            this.ResumeLayout(false);
        }
    }
}
