using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace IAD.Pages
{
    partial class ProductDefinitionPage
    {
        private IContainer components = null;
        private TableLayoutPanel rootLayout;
        private TableLayoutPanel commandLayout;
        private FlowLayoutPanel commandButtons;
        private Button btnSave;
        private Button btnBuildTemplate;
        private Button btnTestLocalization;
        private Button btnVersion;
        private Label lblVersion;
        private GroupBox grpBasicInfo;
        private TableLayoutPanel basicLayout;
        private Label lblProductName;
        private TextBox txtProductName;
        private Label lblProductCode;
        private TextBox txtProductCode;
        private Label lblImageSize;
        private TextBox txtImageSize;
        private Label lblProductCount;
        private TextBox txtProductCount;
        private Label lblPose;
        private ComboBox cboPose;
        private Label lblAcquisition;
        private TextBox txtAcquisition;
        private TableLayoutPanel middleLayout;
        private GroupBox grpTemplate;
        private TableLayoutPanel templateLayout;
        private FlowLayoutPanel templateButtons;
        private Button btnImportReference;
        private Button btnRectangleRoi;
        private Button btnClearRoi;
        private Button btnFastMode;
        private Button btnFineMode;
        private Button btnAutoMode;
        private Panel pnlTemplateCanvas;
        private Label lblCanvasHint;
        private TableLayoutPanel templateFooter;
        private Label lblReferenceFile;
        private Label lblRoiState;
        private Label lblTemplateType;
        private Label lblLastScore;
        private TableLayoutPanel parameterStack;
        private GroupBox grpLocalization;
        private TableLayoutPanel localizationLayout;
        private Label lblLocalizationMethodKey;
        private ComboBox cboLocalizationMethod;
        private Label lblModelTypeKey;
        private ComboBox cboModelType;
        private Label lblMinScoreKey;
        private TextBox txtMinScore;
        private Label lblAngleRangeKey;
        private TextBox txtAngleRange;
        private Label lblScaleRangeKey;
        private TextBox txtScaleRange;
        private Label lblMatchCountKey;
        private TextBox txtMatchCount;
        private Label lblLastResultKey;
        private TextBox txtLastResult;
        private GroupBox grpCalibration;
        private TableLayoutPanel calibrationLayout;
        private Label lblPixelXKey;
        private TextBox txtPixelX;
        private Label lblPixelYKey;
        private TextBox txtPixelY;
        private Label lblLengthUnitKey;
        private ComboBox cboLengthUnit;
        private Label lblAreaUnitKey;
        private ComboBox cboAreaUnit;
        private Label lblCalibrationVersionKey;
        private TextBox txtCalibrationVersion;
        private Label lblCalibrationStateKey;
        private ComboBox cboCalibrationState;
        private GroupBox grpDefects;
        private TableLayoutPanel defectLayout;
        private FlowLayoutPanel defectButtons;
        private Button btnAddDefect;
        private Button btnEditDefect;
        private Button btnDeleteDefect;
        private Button btnToggleDefect;
        private Button btnImportDefects;
        private Button btnExportDefects;
        private DataGridView dgvDefects;
        private DataGridViewTextBoxColumn dgvDefectsCol1;
        private DataGridViewTextBoxColumn dgvDefectsCol2;
        private DataGridViewTextBoxColumn dgvDefectsCol3;
        private DataGridViewTextBoxColumn dgvDefectsCol4;
        private DataGridViewTextBoxColumn dgvDefectsCol5;
        private DataGridViewTextBoxColumn dgvDefectsCol6;
        private DataGridViewTextBoxColumn dgvDefectsCol7;
        private DataGridViewTextBoxColumn dgvDefectsCol8;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new Container();
            this.rootLayout = new TableLayoutPanel();
            this.commandLayout = new TableLayoutPanel();
            this.commandButtons = new FlowLayoutPanel();
            this.btnSave = new Button();
            this.btnBuildTemplate = new Button();
            this.btnTestLocalization = new Button();
            this.btnVersion = new Button();
            this.lblVersion = new Label();
            this.grpBasicInfo = new GroupBox();
            this.basicLayout = new TableLayoutPanel();
            this.lblProductName = new Label();
            this.txtProductName = new TextBox();
            this.lblProductCode = new Label();
            this.txtProductCode = new TextBox();
            this.lblImageSize = new Label();
            this.txtImageSize = new TextBox();
            this.lblProductCount = new Label();
            this.txtProductCount = new TextBox();
            this.lblPose = new Label();
            this.cboPose = new ComboBox();
            this.lblAcquisition = new Label();
            this.txtAcquisition = new TextBox();
            this.middleLayout = new TableLayoutPanel();
            this.grpTemplate = new GroupBox();
            this.templateLayout = new TableLayoutPanel();
            this.templateButtons = new FlowLayoutPanel();
            this.btnImportReference = new Button();
            this.btnRectangleRoi = new Button();
            this.btnClearRoi = new Button();
            this.btnFastMode = new Button();
            this.btnFineMode = new Button();
            this.btnAutoMode = new Button();
            this.pnlTemplateCanvas = new Panel();
            this.lblCanvasHint = new Label();
            this.templateFooter = new TableLayoutPanel();
            this.lblReferenceFile = new Label();
            this.lblRoiState = new Label();
            this.lblTemplateType = new Label();
            this.lblLastScore = new Label();
            this.parameterStack = new TableLayoutPanel();
            this.grpLocalization = new GroupBox();
            this.localizationLayout = new TableLayoutPanel();
            this.lblLocalizationMethodKey = new Label();
            this.cboLocalizationMethod = new ComboBox();
            this.lblModelTypeKey = new Label();
            this.cboModelType = new ComboBox();
            this.lblMinScoreKey = new Label();
            this.txtMinScore = new TextBox();
            this.lblAngleRangeKey = new Label();
            this.txtAngleRange = new TextBox();
            this.lblScaleRangeKey = new Label();
            this.txtScaleRange = new TextBox();
            this.lblMatchCountKey = new Label();
            this.txtMatchCount = new TextBox();
            this.lblLastResultKey = new Label();
            this.txtLastResult = new TextBox();
            this.grpCalibration = new GroupBox();
            this.calibrationLayout = new TableLayoutPanel();
            this.lblPixelXKey = new Label();
            this.txtPixelX = new TextBox();
            this.lblPixelYKey = new Label();
            this.txtPixelY = new TextBox();
            this.lblLengthUnitKey = new Label();
            this.cboLengthUnit = new ComboBox();
            this.lblAreaUnitKey = new Label();
            this.cboAreaUnit = new ComboBox();
            this.lblCalibrationVersionKey = new Label();
            this.txtCalibrationVersion = new TextBox();
            this.lblCalibrationStateKey = new Label();
            this.cboCalibrationState = new ComboBox();
            this.grpDefects = new GroupBox();
            this.defectLayout = new TableLayoutPanel();
            this.defectButtons = new FlowLayoutPanel();
            this.btnAddDefect = new Button();
            this.btnEditDefect = new Button();
            this.btnDeleteDefect = new Button();
            this.btnToggleDefect = new Button();
            this.btnImportDefects = new Button();
            this.btnExportDefects = new Button();
            this.dgvDefects = new DataGridView();
            this.dgvDefectsCol1 = new DataGridViewTextBoxColumn();
            this.dgvDefectsCol2 = new DataGridViewTextBoxColumn();
            this.dgvDefectsCol3 = new DataGridViewTextBoxColumn();
            this.dgvDefectsCol4 = new DataGridViewTextBoxColumn();
            this.dgvDefectsCol5 = new DataGridViewTextBoxColumn();
            this.dgvDefectsCol6 = new DataGridViewTextBoxColumn();
            this.dgvDefectsCol7 = new DataGridViewTextBoxColumn();
            this.dgvDefectsCol8 = new DataGridViewTextBoxColumn();
            ((ISupportInitialize)(this.dgvDefects)).BeginInit();
            this.SuspendLayout();

            this.rootLayout.BackColor = Color.FromArgb(247, 247, 247);
            this.rootLayout.ColumnCount = 1;
            this.rootLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.rootLayout.Dock = DockStyle.Fill;
            this.rootLayout.Name = "rootLayout";
            this.rootLayout.RowCount = 4;
            this.rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));
            this.rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 126F));
            this.rootLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 62F));
            this.rootLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 38F));

            this.commandLayout.ColumnCount = 2;
            this.commandLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            this.commandLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 400F));
            this.commandLayout.Dock = DockStyle.Fill;
            this.commandLayout.Name = "commandLayout";
            this.commandButtons.Dock = DockStyle.Fill;
            this.commandButtons.FlowDirection = FlowDirection.LeftToRight;
            this.commandButtons.Padding = new Padding(0, 5, 0, 5);
            this.commandButtons.WrapContents = false;

            this.btnSave.Text = "保存产品定义";
            this.btnSave.Width = 112;
            this.btnBuildTemplate.Text = "建立 / 更新模板";
            this.btnBuildTemplate.Width = 128;
            this.btnTestLocalization.Text = "测试定位";
            this.btnTestLocalization.Width = 92;
            this.btnVersion.Text = "版本记录";
            this.btnVersion.Width = 92;
            this.commandButtons.Controls.Add(this.btnSave);
            this.commandButtons.Controls.Add(this.btnBuildTemplate);
            this.commandButtons.Controls.Add(this.btnTestLocalization);
            this.commandButtons.Controls.Add(this.btnVersion);
            this.lblVersion.Dock = DockStyle.Fill;
            this.lblVersion.ForeColor = Color.DimGray;
            this.lblVersion.Text = "产品定义版本：PD-1.0.0    模板版本：LT-1.0.0    状态：已配置";
            this.lblVersion.TextAlign = ContentAlignment.MiddleRight;
            this.commandLayout.Controls.Add(this.commandButtons, 0, 0);
            this.commandLayout.Controls.Add(this.lblVersion, 1, 0);

            this.grpBasicInfo.BackColor = Color.White;
            this.grpBasicInfo.Dock = DockStyle.Fill;
            this.grpBasicInfo.Font = new Font("Microsoft YaHei UI", 10F, FontStyle.Bold);
            this.grpBasicInfo.Text = "产品基本信息";
            this.grpBasicInfo.Controls.Add(this.basicLayout);
            this.basicLayout.ColumnCount = 6;
            this.basicLayout.Dock = DockStyle.Fill;
            this.basicLayout.RowCount = 2;
            this.basicLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
            this.basicLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            this.basicLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 18F));
            this.basicLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 18F));
            this.basicLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 18F));
            this.basicLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 14F));
            this.basicLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 14F));
            this.basicLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 18F));
            this.lblProductName.Text = "产品名称";
            this.txtProductName.Text = "轴承盖板";
            this.lblProductCode.Text = "产品编号";
            this.txtProductCode.Text = "P-20250516-001";
            this.lblImageSize.Text = "图像尺寸";
            this.txtImageSize.Text = "2448 × 2048 px";
            this.lblProductCount.Text = "单图产品数";
            this.txtProductCount.Text = "1";
            this.lblPose.Text = "姿态";
            this.cboPose.DropDownStyle = ComboBoxStyle.DropDownList;
            this.cboPose.Items.AddRange(new object[] { "固定", "允许旋转" });
            this.cboPose.SelectedIndex = 1;
            this.lblAcquisition.Text = "采集条件";
            this.txtAcquisition.Text = "相机 / 光照 / 背景稳定";
            this.basicLayout.Controls.Add(this.lblProductName, 0, 0);
            this.basicLayout.Controls.Add(this.txtProductName, 0, 1);
            this.basicLayout.Controls.Add(this.lblProductCode, 1, 0);
            this.basicLayout.Controls.Add(this.txtProductCode, 1, 1);
            this.basicLayout.Controls.Add(this.lblImageSize, 2, 0);
            this.basicLayout.Controls.Add(this.txtImageSize, 2, 1);
            this.basicLayout.Controls.Add(this.lblProductCount, 3, 0);
            this.basicLayout.Controls.Add(this.txtProductCount, 3, 1);
            this.basicLayout.Controls.Add(this.lblPose, 4, 0);
            this.basicLayout.Controls.Add(this.cboPose, 4, 1);
            this.basicLayout.Controls.Add(this.lblAcquisition, 5, 0);
            this.basicLayout.Controls.Add(this.txtAcquisition, 5, 1);

            this.middleLayout.ColumnCount = 2;
            this.middleLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 64F));
            this.middleLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 36F));
            this.middleLayout.Dock = DockStyle.Fill;
            this.grpTemplate.BackColor = Color.White;
            this.grpTemplate.Dock = DockStyle.Fill;
            this.grpTemplate.Font = new Font("Microsoft YaHei UI", 10F, FontStyle.Bold);
            this.grpTemplate.Text = "产品模板与 ROI";
            this.grpTemplate.Controls.Add(this.templateLayout);
            this.templateLayout.ColumnCount = 1;
            this.templateLayout.Dock = DockStyle.Fill;
            this.templateLayout.RowCount = 3;
            this.templateLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 42F));
            this.templateLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            this.templateLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 36F));
            this.templateButtons.Dock = DockStyle.Fill;
            this.templateButtons.WrapContents = false;
            this.btnImportReference.Text = "导入基准图";
            this.btnRectangleRoi.Text = "Rectangle ROI";
            this.btnClearRoi.Text = "清除 ROI";
            this.btnFastMode.Text = "快速模式";
            this.btnFineMode.Text = "精细模式";
            this.btnAutoMode.Text = "自动模式";
            this.templateButtons.Controls.Add(this.btnImportReference);
            this.templateButtons.Controls.Add(this.btnRectangleRoi);
            this.templateButtons.Controls.Add(this.btnClearRoi);
            this.templateButtons.Controls.Add(this.btnFastMode);
            this.templateButtons.Controls.Add(this.btnFineMode);
            this.templateButtons.Controls.Add(this.btnAutoMode);
            this.pnlTemplateCanvas.BackColor = Color.FromArgb(40, 40, 40);
            this.pnlTemplateCanvas.BorderStyle = BorderStyle.FixedSingle;
            this.pnlTemplateCanvas.Dock = DockStyle.Fill;
            this.pnlTemplateCanvas.Controls.Add(this.lblCanvasHint);
            this.lblCanvasHint.Dock = DockStyle.Fill;
            this.lblCanvasHint.ForeColor = Color.Gainsboro;
            this.lblCanvasHint.Font = new Font("Microsoft YaHei UI", 10F);
            this.lblCanvasHint.Text = "基准图预览\r\n\r\n在此显示产品图像与 Template ROI\r\n可在功能代码中接入 HALCON HWindowControl";
            this.lblCanvasHint.TextAlign = ContentAlignment.MiddleCenter;
            this.templateFooter.ColumnCount = 4;
            this.templateFooter.Dock = DockStyle.Fill;
            this.templateFooter.BackColor = Color.FromArgb(244, 244, 244);
            this.templateFooter.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
            this.templateFooter.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
            this.templateFooter.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
            this.templateFooter.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 25F));
            this.lblReferenceFile.Text = "基准图：reference_001.png";
            this.lblRoiState.Text = "ROI：已定义";
            this.lblTemplateType.Text = "定位模板：Shape Model";
            this.lblLastScore.Text = "最近测试：Score 0.92";
            this.templateFooter.Controls.Add(this.lblReferenceFile, 0, 0);
            this.templateFooter.Controls.Add(this.lblRoiState, 1, 0);
            this.templateFooter.Controls.Add(this.lblTemplateType, 2, 0);
            this.templateFooter.Controls.Add(this.lblLastScore, 3, 0);
            this.templateLayout.Controls.Add(this.templateButtons, 0, 0);
            this.templateLayout.Controls.Add(this.pnlTemplateCanvas, 0, 1);
            this.templateLayout.Controls.Add(this.templateFooter, 0, 2);

            this.parameterStack.ColumnCount = 1;
            this.parameterStack.Dock = DockStyle.Fill;
            this.parameterStack.RowCount = 2;
            this.parameterStack.RowStyles.Add(new RowStyle(SizeType.Percent, 58F));
            this.parameterStack.RowStyles.Add(new RowStyle(SizeType.Percent, 42F));
            this.grpLocalization.BackColor = Color.White;
            this.grpLocalization.Dock = DockStyle.Fill;
            this.grpLocalization.Text = "定位参数";
            this.grpLocalization.Controls.Add(this.localizationLayout);
            this.localizationLayout.ColumnCount = 2;
            this.localizationLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 40F));
            this.localizationLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 60F));
            this.localizationLayout.Dock = DockStyle.Fill;
            this.localizationLayout.RowCount = 7;
            this.lblLocalizationMethodKey.Text = "定位方式";
            this.cboLocalizationMethod.Items.AddRange(new object[] { "HALCON Shape Matching", "特征匹配" });
            this.cboLocalizationMethod.SelectedIndex = 0;
            this.lblModelTypeKey.Text = "模型类型";
            this.cboModelType.Items.AddRange(new object[] { "Shape Model", "NCC Model" });
            this.cboModelType.SelectedIndex = 0;
            this.lblMinScoreKey.Text = "最小匹配分数";
            this.txtMinScore.Text = "0.60";
            this.lblAngleRangeKey.Text = "角度范围";
            this.txtAngleRange.Text = "-30° ~ 30°";
            this.lblScaleRangeKey.Text = "缩放范围";
            this.txtScaleRange.Text = "90% ~ 110%";
            this.lblMatchCountKey.Text = "匹配个数";
            this.txtMatchCount.Text = "1";
            this.lblLastResultKey.Text = "最近定位结果";
            this.txtLastResult.Text = "Row 1024.32 / Col 1226.78 / Angle -1.24° / Score 0.92";
            this.localizationLayout.Controls.Add(this.lblLocalizationMethodKey, 0, 0);
            this.localizationLayout.Controls.Add(this.cboLocalizationMethod, 1, 0);
            this.localizationLayout.Controls.Add(this.lblModelTypeKey, 0, 1);
            this.localizationLayout.Controls.Add(this.cboModelType, 1, 1);
            this.localizationLayout.Controls.Add(this.lblMinScoreKey, 0, 2);
            this.localizationLayout.Controls.Add(this.txtMinScore, 1, 2);
            this.localizationLayout.Controls.Add(this.lblAngleRangeKey, 0, 3);
            this.localizationLayout.Controls.Add(this.txtAngleRange, 1, 3);
            this.localizationLayout.Controls.Add(this.lblScaleRangeKey, 0, 4);
            this.localizationLayout.Controls.Add(this.txtScaleRange, 1, 4);
            this.localizationLayout.Controls.Add(this.lblMatchCountKey, 0, 5);
            this.localizationLayout.Controls.Add(this.txtMatchCount, 1, 5);
            this.localizationLayout.Controls.Add(this.lblLastResultKey, 0, 6);
            this.localizationLayout.Controls.Add(this.txtLastResult, 1, 6);

            this.grpCalibration.BackColor = Color.White;
            this.grpCalibration.Dock = DockStyle.Fill;
            this.grpCalibration.Text = "尺寸标定";
            this.grpCalibration.Controls.Add(this.calibrationLayout);
            this.calibrationLayout.ColumnCount = 2;
            this.calibrationLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 40F));
            this.calibrationLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 60F));
            this.calibrationLayout.Dock = DockStyle.Fill;
            this.calibrationLayout.RowCount = 6;
            this.lblPixelXKey.Text = "像素尺寸 X";
            this.txtPixelX.Text = "6.5000 μm/px";
            this.lblPixelYKey.Text = "像素尺寸 Y";
            this.txtPixelY.Text = "6.5000 μm/px";
            this.lblLengthUnitKey.Text = "长度单位";
            this.cboLengthUnit.Items.AddRange(new object[] { "mm", "px" });
            this.cboLengthUnit.SelectedIndex = 0;
            this.lblAreaUnitKey.Text = "面积单位";
            this.cboAreaUnit.Items.AddRange(new object[] { "mm²", "px²" });
            this.cboAreaUnit.SelectedIndex = 0;
            this.lblCalibrationVersionKey.Text = "标定版本";
            this.txtCalibrationVersion.Text = "CV-1.0.2";
            this.lblCalibrationStateKey.Text = "状态";
            this.cboCalibrationState.Items.AddRange(new object[] { "有效", "无效" });
            this.cboCalibrationState.SelectedIndex = 0;
            this.calibrationLayout.Controls.Add(this.lblPixelXKey, 0, 0);
            this.calibrationLayout.Controls.Add(this.txtPixelX, 1, 0);
            this.calibrationLayout.Controls.Add(this.lblPixelYKey, 0, 1);
            this.calibrationLayout.Controls.Add(this.txtPixelY, 1, 1);
            this.calibrationLayout.Controls.Add(this.lblLengthUnitKey, 0, 2);
            this.calibrationLayout.Controls.Add(this.cboLengthUnit, 1, 2);
            this.calibrationLayout.Controls.Add(this.lblAreaUnitKey, 0, 3);
            this.calibrationLayout.Controls.Add(this.cboAreaUnit, 1, 3);
            this.calibrationLayout.Controls.Add(this.lblCalibrationVersionKey, 0, 4);
            this.calibrationLayout.Controls.Add(this.txtCalibrationVersion, 1, 4);
            this.calibrationLayout.Controls.Add(this.lblCalibrationStateKey, 0, 5);
            this.calibrationLayout.Controls.Add(this.cboCalibrationState, 1, 5);
            this.parameterStack.Controls.Add(this.grpLocalization, 0, 0);
            this.parameterStack.Controls.Add(this.grpCalibration, 0, 1);
            this.middleLayout.Controls.Add(this.grpTemplate, 0, 0);
            this.middleLayout.Controls.Add(this.parameterStack, 1, 0);

            this.grpDefects.BackColor = Color.White;
            this.grpDefects.Dock = DockStyle.Fill;
            this.grpDefects.Font = new Font("Microsoft YaHei UI", 10F, FontStyle.Bold);
            this.grpDefects.Text = "缺陷类别管理";
            this.grpDefects.Controls.Add(this.defectLayout);
            this.defectLayout.ColumnCount = 1;
            this.defectLayout.Dock = DockStyle.Fill;
            this.defectLayout.RowCount = 2;
            this.defectLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 40F));
            this.defectLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            this.defectButtons.Dock = DockStyle.Fill;
            this.defectButtons.WrapContents = false;
            this.btnAddDefect.Text = "新增类别";
            this.btnEditDefect.Text = "编辑类别";
            this.btnDeleteDefect.Text = "删除类别";
            this.btnToggleDefect.Text = "启用 / 停用";
            this.btnImportDefects.Text = "导入配置";
            this.btnExportDefects.Text = "导出配置";
            this.defectButtons.Controls.Add(this.btnAddDefect);
            this.defectButtons.Controls.Add(this.btnEditDefect);
            this.defectButtons.Controls.Add(this.btnDeleteDefect);
            this.defectButtons.Controls.Add(this.btnToggleDefect);
            this.defectButtons.Controls.Add(this.btnImportDefects);
            this.defectButtons.Controls.Add(this.btnExportDefects);
            this.dgvDefects.AllowUserToAddRows = false;
            this.dgvDefects.AllowUserToDeleteRows = false;
            this.dgvDefects.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvDefects.BackgroundColor = Color.White;
            this.dgvDefects.Dock = DockStyle.Fill;
            this.dgvDefects.ReadOnly = true;
            this.dgvDefects.RowHeadersVisible = false;
            this.dgvDefects.Columns.AddRange(new DataGridViewColumn[] { this.dgvDefectsCol1, this.dgvDefectsCol2, this.dgvDefectsCol3, this.dgvDefectsCol4, this.dgvDefectsCol5, this.dgvDefectsCol6, this.dgvDefectsCol7, this.dgvDefectsCol8 });
            this.dgvDefectsCol1.HeaderText = "序号";
            this.dgvDefectsCol2.HeaderText = "缺陷名称";
            this.dgvDefectsCol3.HeaderText = "缺陷类型";
            this.dgvDefectsCol4.HeaderText = "检测策略";
            this.dgvDefectsCol5.HeaderText = "默认阈值";
            this.dgvDefectsCol6.HeaderText = "最小面积(px)";
            this.dgvDefectsCol7.HeaderText = "最小长度(px)";
            this.dgvDefectsCol8.HeaderText = "状态";
            this.defectLayout.Controls.Add(this.defectButtons, 0, 0);
            this.defectLayout.Controls.Add(this.dgvDefects, 0, 1);

            this.rootLayout.Controls.Add(this.commandLayout, 0, 0);
            this.rootLayout.Controls.Add(this.grpBasicInfo, 0, 1);
            this.rootLayout.Controls.Add(this.middleLayout, 0, 2);
            this.rootLayout.Controls.Add(this.grpDefects, 0, 3);
            this.AutoScaleDimensions = new SizeF(8F, 15F);
            this.AutoScaleMode = AutoScaleMode.Font;
            this.BackColor = Color.FromArgb(247, 247, 247);
            this.Controls.Add(this.rootLayout);
            this.Name = "ProductDefinitionPage";
            this.Padding = new Padding(14, 12, 4, 10);
            this.Size = new Size(1400, 820);
            ((ISupportInitialize)(this.dgvDefects)).EndInit();
            this.ResumeLayout(false);
        }
    }
}
