name: WinForms Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore
        run: msbuild IAD.sln /t:Restore /p:RestorePackagesConfig=true

      - name: Build
        run: msbuild IAD.sln /t:Rebuild /p:Configuration=Debug /p:Platform=x64 /m /v:minimal
